const keys=new Set(),player={x:50,y:82,speed:.55},zero=document.querySelector("#zero"),cards=[...document.querySelectorAll(".cartao")],feedback=document.querySelector("#feedback"),connected=new Set(),total=5;let selected,nearby,completed=false,lives=3;
const say=(text,type="")=>{feedback.textContent=text;feedback.className=type};
function updateHud(){document.querySelector("#combination").textContent=`${connected.size} / ${total}`;document.querySelector("#generatedCode").textContent=connected.size===total?"CONEXÕES COMPLETAS":`${connected.size} DE ${total} CONEXÕES`;document.querySelector("#hearts").textContent="♥ ".repeat(lives).trim()+" ♡".repeat(3-lives)}
function distance(card){const p=zero.getBoundingClientRect(),c=card.getBoundingClientRect();return Math.hypot(p.left+p.width/2-c.left-c.width/2,p.top+p.height/2-c.top-c.height/2)}
function updateNearby(){nearby=cards.find(c=>!c.classList.contains("conectado")&&distance(c)<105);cards.forEach(c=>c.classList.toggle("perto",c===nearby));if(completed||lives===0)return;if(nearby)say(nearby.classList.contains("codigo")?"APERTE F PARA SELECIONAR O CÓDIGO":"APERTE F PARA CONECTAR O SIGNIFICADO");else if(selected)say(`Encontre o significado de ${selected.querySelector("b").textContent}.`);else say("Explore a sala com W A S D.")}
function loseLife(){lives--;selected?.classList.remove("selecionado");selected=null;updateHud();if(!lives){document.querySelector("#gameOver").style.display="flex";say("Suas tentativas acabaram.","erro")}else say(`CONEXÃO INCORRETA. Restam ${lives} coração${lives===1?"":"ões"}.`,"erro")}
function interact(){if(!nearby||completed||!lives)return;if(nearby.classList.contains("codigo")){selected?.classList.remove("selecionado");selected=nearby;selected.classList.add("selecionado");say(`Você escolheu ${selected.querySelector("b").textContent}. Encontre o significado dele.`);return}if(!selected)return say("Primeiro selecione um trecho de código à esquerda.","erro");if(selected.dataset.id!==nearby.dataset.id)return loseLife();selected.classList.replace("selecionado","conectado");nearby.classList.add("conectado");connected.add(selected.dataset.id);selected=null;updateHud();if(connected.size===total){completed=true;document.querySelector("#porta").classList.add("aberta");say("TODAS AS CONEXÕES ESTÃO CORRETAS!","ok");document.querySelector("#complete").style.display="flex"}else say("CONEXÃO CORRETA! Encontre o próximo código.","ok")}
function move(){if(keys.has("a"))player.x-=player.speed;if(keys.has("d"))player.x+=player.speed;if(keys.has("w"))player.y-=player.speed;if(keys.has("s"))player.y+=player.speed;player.x=Math.max(5,Math.min(95,player.x));player.y=Math.max(10,Math.min(90,player.y));zero.style.left=`${player.x}%`;zero.style.top=`${player.y}%`;updateNearby();requestAnimationFrame(move)}
document.addEventListener("keydown",e=>{const k=e.key.toLowerCase();if(["w","a","s","d","f"].includes(k))e.preventDefault();if(["w","a","s","d"].includes(k))keys.add(k);if(k==="f"&&!e.repeat)interact()});document.addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));cards.forEach(c=>c.addEventListener("click",()=>distance(c)<150?(nearby=c,interact()):say("Chegue mais perto deste cartão.")));document.querySelector("#restartButton").onclick=()=>location.reload();document.querySelector("#nextButton").onclick=async()=>{if(window.SaveSystem)await SaveSystem.updateActivePhase(3);else localStorage.setItem("faseAtual","3");location.href="lobby.html"};
const opening=document.querySelector("#aberturaFase2"),speech=document.querySelector("#falaFase2"),lines=["A porta está trancada.","Há cinco partes de código espalhadas pela sala.","Aproxime-se de uma tag e aperte F; depois conecte-a ao significado correto.","Você tem três corações: cada erro tira uma tentativa.","Faça todas as conexões para abrir a porta."];let line=0;speech.textContent=lines[0];speech.onclick=()=>++line>=lines.length?opening.classList.add("encerrada"):speech.textContent=lines[line];updateHud();requestAnimationFrame(move);
